http:
  middlewares:
    redirect:
      redirectScheme:
        scheme: https
        permanent: true
    error:
      errors:
        status:
          - "429"
        service: serviceError
        query: "errorrr"
    ratelimit:
      rateLimit:
        average: 4
        period: 2s
    accblock:
      plugin:
        accblock:
          accounts:
            "ds-partner-stg": ["192.168.1.0/24", "192.168.2.0/24"]
            "ds-customer-stg": ["10.0.0.0/8"]
            "ds-inventories": ["172.16.0.0/16"]


  routers:
    allbackendRouter:
      rule: Host(`localhost`) && Path(`/`)
      entryPoints:
        - http
      middlewares:
        - ratelimit
        # - accblock
      service: allbackend
    app1router:
      rule: Host(`app1.localhost`)
      entryPoints:
        - http
      service: app1
    app2router:
      rule: Host(`app2.localhost`)
      entryPoints:
        - http
      service: app2
    weighted-svc-router:
      rule: Host(`weighted-svc.localhost`)
      entryPoints:
        - http
      service: weighted-svc
  services:
    allbackend:
      loadBalancer:
        servers:
          - url: http://localhost:9991
          - url: http://localhost:9992
          - url: http://localhost:9993
          - url: http://localhost:9994
    app1:
      loadBalancer:
        servers:
          - url: http://localhost:9991
    app2:
      loadBalancer:
        servers:
          - url: http://localhost:9992
    app3:
      loadBalancer:
        servers:
          - url: http://localhost:9993
    app4:
      loadBalancer:
        servers:
          - url: http://localhost:9994
    weighted-svc:
      weighted:
        services:
          - name: app1
            weight: 3
          - name: app2
            weight: 1
          - name: app3
            weight: 1
          - name: app4
            weight: 1
