http:
  routers:
    allbackendRouter:
      rule: Host(`localhost`) && Path(`/`)
      entryPoints:
        - http
      service: allbackend
    app1router:
      rule: Host(`app1.localhost`)
      entryPoints:
        - http
      service: app1
    app2router:
      rule: Host(`app2.localhost`)
      entryPoints:
        - http
      service: app2
    weighted-svc-router:
      rule: Host(`weighted-svc.localhost`)
      entryPoints:
        - http
      service: weighted-svc
  services:
    allbackend:
      loadBalancer:
        servers:
          - url: http://localhost:9991
          - url: http://localhost:9992
          - url: http://localhost:9993
          - url: http://localhost:9994
    app1:
      loadBalancer:
        servers:
          - url: http://localhost:9991
    app2:
      loadBalancer:
        servers:
          - url: http://localhost:9992
    weighted-svc:
      weighted:
        services:
          - name: app1
            weight: 100
          - name: app2
            weight: 0
