apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-actions-runner
  template:
    metadata:
      labels:
        app: github-actions-runner
    spec:
      containers:
      - name: runner
        image: moabukar/gh-runner-basic:6c2485a
        env:
          - name: GITHUB_RUNNER_TOKEN
            valueFrom:
              secretKeyRef:
                name: gh-runner-secret
                key: GITHUB_RUNNER_TOKEN
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
