## For use when pushing a light nginx image for a test ECS service
#FROM nginx:stable-alpine3.17-slim
#FROM nginx:latest


## For use when pushing a light apache/httpd image for a test ECS service
# FROM httpd:alpine3.19
FROM httpd
