version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      - "traefik.http.middlewares.mw-auth-htpasswd.basicauth.usersfile=/.htpasswd"
      - "traefik.http.middlewares.mw-auth-htpasswd.basicauth.realm=localhost"

      # Middleware config: Add mTLS information into header
      - "traefik.http.middlewares.mw-cert.passtlsclientcert.pem=true"
      - "traefik.http.middlewares.mw-cert.passtlsclientcert.info.sans=true"
      - "traefik.http.middlewares.mw-cert.passtlsclientcert.info.subject.commonname=true"
      - "traefik.http.middlewares.mw-cert.passtlsclientcert.info.subject.serialnumber=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  api-mtls:
    image: python:3.9
    command: bash -c "python3 -m pip install fastapi uvicorn && python3 -m uvicorn app.main:app --host 0.0.0.0 --reload"
    # networks:
    #   - t_nwk
    volumes:
      - ./app2.py:/app/main.py:ro
    expose:
      - "8000"
    labels:
     - "traefik.enable=true"
      # > 'api.mtls.localhost' section
     - "traefik.http.routers.api-mtls.rule=Host(`api.mtls.localhost`)"
     - "traefik.http.routers.api-mtls.entryPoints=websecure"
     - "traefik.http.routers.api-mtls.tls=true"
     - "traefik.http.routers.api-mtls.tls.options=mtls-required@file"
     - "traefik.http.routers.api-mtls.middlewares=mw-cert@docker"
