http:
  routers:
    dashboard:
      rule: "Host(`mo.test`)"
      service: "noop@internal"
      entryPoints:
        - "http"
      middlewares:
        - "secured-redirect"
    dashboard-secured:
      entryPoints:
        - "https"
      rule: "Host(`mo.test`)"
      service: "api@internal"
      tls:
        certResolver: "local"
        domains:
          - main: "mo.test"

    moab:
      rule: "Host(`mo.ab`)"
      service: "noop@internal"
      entryPoints:
        - "http"
      middlewares:
        - "secured-redirect"
    moab-secured:
      entryPoints:
        - "https"
      rule: "Host(`mo.ab`)"
      service: "example-service"
      tls:
        certResolver: "local"
        options: acmeClient
        domains:
          - main: "mo.ab"          

  middlewares:
    secured-redirect:
      redirectscheme:
        scheme: https
        permanent: true

  services:
    example-service:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://localhost:8080/"

tls:
  options:
    acmeClient:
      clientAuth:
        caFiles:
          - /Users/mohameda/.step/authorities/test.ca/certs/root_ca.crt
# the path of root certificate might be like below:-
# <USER_HOME>/.step/authorities/test.ca/certs/root_ca.crt
        clientAuthType: RequireAndVerifyClientCert

log:
  filePath: log-file.log # relative to current location, will be created
  level: DEBUG
