# Use for local testing so you don't have to supply all
# environment variables.

providers:
  file:
    # directory: /Users/mohameda/Documents/Learning/playground/traefik-error-pages
    directory: .
    watch: true
    # http:
    #   endpoint: http://host.docker.internal
    # docker:
    #   endpoint: "unix:///var/run/docker.sock"
    #   #endpoint: 127.0.0.1
    #   exposedByDefault: true
    #   useBindPortIP: true

#traefikerrors.ddns.net

ping:
  entryPoint: "traefik"

entryPoints:
  http:
    address: ":80"
  websecure:
    address: ":443"
  metrics:
    address: ":8082"
  traefik:
    address: ":8080"
    # jaeger:
    #   address: ":5778"

# API and dashboard configuration
api:
  insecure: true
  dashboard: true

accessLog:
  format: json
  fields:
    headers:
      defaultMode: keep
  filePath: access.log
  filters:
    statusCodes:
    - "200"
    - "300-304"
    - "502"
    retryAttempts: true
    minDuration: "10ms"
log:
  format: json
  # level: DEBUG

metrics:
  prometheus:
    addRoutersLabels: true
    addEntryPointsLabels: true
    addServicesLabels: true
    entryPoint: "metrics"


certificatesResolvers:
  myresolver:
    acme:
      email: moabukar9@gmail.com
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      storage: acme.json
      # dnsChallenge:
      #   provider: manual
      #   disablePropagationCheck: true
      #   delayBeforeCheck: 0
      httpChallenge:
        entryPoint: http
      tlsChallenge: {}

  letsencrypt:
    acme:
      email: moabukar9@gmail.com
      httpChallenge:
        entryPoint: http


  # tracing:
  #   jaeger:
  #     # entryPoint: "jaeger"
  #     samplingServerURL: http://localhost:5778/sampling
  #     localAgentHostPort: "localhost:6831"
  #     # collector:
  #     #     endpoint: http://127.0.0.1:14268/api/traces?format=jaeger.thrift

  # experimental:
  #   localPlugins:
  #     accblock:
  #       moduleName: github.com/moabukar/accblock
  # plugins:
  #   fail2ban:
  #     moduleName: "github.com/tomMoulard/fail2ban"
  #     version: "v0.7.1"
