scrape_configs:
  - job_name: service-a
    scrape_interval: 1s
    static_configs:
      - targets: ['a.service:8081']

  - job_name: service-a-envoy
    scrape_interval: 1s
    metrics_path: /stats/prometheus
    static_configs:
      - targets: ['a.service:9901']

  - job_name: service-b
    scrape_interval: 1s
    static_configs:
      - targets: ['b.service:8081']

