apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nats
  namespace: nats
spec:
  releaseName: nats
  chart:
    spec:
      chart: nats
      version: 1.1.9
      sourceRef:
        kind: HelmRepository
        name: nats
        namespace: flux-system
  interval: 15m0s
  values:
    config:
      cluster:
        enabled: true
        replicas: 3      
    container:
      image:
        repository: nats
        tag: 2.10.12-alpine
        registry: AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/docker-hub/library
    reloader:
      image:
        repository: natsio/nats-server-config-reloader
        pullPolicy: IfNotPresent
        registry: AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/docker-hub
