apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-private
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: external-dns-private
  template:
    metadata:
      labels:
        app: external-dns-private
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/k8s/external-dns/external-dns:v0.14.0
        args:
        - --source=service
        - --source=ingress
        - --provider=aws
        - --annotation-filter=private-hosted-zone-record in (true, True, TRUE)
        - --aws-zone-type=private
        - --registry=txt
      securityContext:
        fsGroup: 65534
