name: error-pages CLI

on:
  push:
    paths:
      - .github/workflows/error-pages-publish.yml
      - traefik-basic/error-pages/**

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Publish
      run: |
        registry="moabukar"
        dir=./traefik-basic/error-pages/
        file=Dockerfile
        sha=$(git rev-parse --short HEAD)
        primary_tag="${registry}/error-pages:${sha}"
        
        docker build -t $primary_tag $dir -f $dir/$file
        docker push $primary_tag

        current_branch=$(git rev-parse --abbrev-ref HEAD)
        if [ "$current_branch" = "main" ]; then
          retention_tag="${registry}/error-pages:rc-${sha}"
          docker tag $primary_tag $retention_tag
          docker push $retention_tag
        else
          retention_tag="${registry}/error-pages:alpha-${sha}"
          docker tag $primary_tag $retention_tag
          docker push $retention_tag
        fi
