# name: gh-runner-basic CLI

# on:
#   push:
#     paths:
#       - .github/workflows/k8s-runner.yml
#       - gh-runner-basic/**

# jobs:
#   build-and-publish:
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write
#       contents: write

#     steps:
#     - name: Check out
#       uses: actions/checkout@v2

#     - name: Log in to Docker Hub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_HUB_USERNAME }}
#         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#     - name: Build and Publish
#       run: |
#         registry="moabukar"
#         dir=./gh-runner-basic/
#         file=Dockerfile
#         sha=$(git rev-parse --short HEAD)
#         primary_tag="${registry}/gh-runner-basic:${sha}"
        
#         docker build -t $primary_tag $dir -f $dir/$file
#         docker push $primary_tag

#         current_branch=$(git rev-parse --abbrev-ref HEAD)
#         if [ "$current_branch" = "main" ]; then
#           retention_tag="${registry}/gh-runner-basic:rc-${sha}"
#           docker tag $primary_tag $retention_tag
#           docker push $retention_tag
#         else
#           retention_tag="${registry}/gh-runner-basic:alpha-${sha}"
#           docker tag $primary_tag $retention_tag
#           docker push $retention_tag
#         fi

name: gh-runner-basic CLI

on:
  push:
    paths:
      - .github/workflows/k8s-runner.yml
      - gh-runner-basic/**

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: ./gh-runner-basic/
        file: ./gh-runner-basic/Dockerfile
        build-args: |
          GITHUB_RUNNER_VERSION=${{ env.GITHUB_RUNNER_VERSION }}
          RUNNER_ARCH=arm64
        push: true
        tags: |
          moabukar/gh-runner-basic:${{ github.sha }}
          moabukar/gh-runner-basic:latest
        platforms: linux/amd64,linux/arm64

    - name: Retain Image
      if: github.ref == 'refs/heads/main'
      run: |
        registry="moabukar"
        sha=$(git rev-parse --short HEAD)
        primary_tag="${registry}/gh-runner-basic:${sha}"
        retention_tag="${registry}/gh-runner-basic:rc-${sha}"
        
        echo "Tagging image for retention as ${retention_tag}"
        docker pull $primary_tag
        docker tag $primary_tag $retention_tag
        docker push $retention_tag
